# Generated by Django 2.2.4 on 2019-08-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0073_interface_form_factor_to_type'),
        ('dcim', '0070_imrpove_audio_interfaces'),
    ]

    operations = [
    ]
