# Generated by Django 3.0.5 on 2020-04-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0104_correct_infiniband_types'),
        ('dcim', '0074_merge_20190809_1449'),
    ]

    operations = [
    ]
