# Generated by Django 3.0.5 on 2020-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0105_merge_20200423_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interfacetemplate',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
